### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by DennisFaucher** [thebel1/thpimon#5]
Hi. Thanks for the great libraries. Pulling pin state is working great for me. When I try to pull temperature with pimon_util.py, I get this though. Any ideas? I am running ESXi on Arm Fling (Build 17068872) on a Raspberry Pi4. TIA.

] python3 ./pimon_util.py
[Errno 22] Invalid argument
[Errno 22] Invalid argument
Firmware Revision:	0x0
[Errno 22] Invalid argument
Board Model:		0
[Errno 22] Invalid argument
Board Revision:		0x0
Board MAC Address:	0:0:0:0:0:0
[Errno 22] Invalid argument
Board Serial:		0x00000000000000
[Errno 22] Invalid argument
Temp:			0 (deg. C)

**Comment by DennisFaucher** [comment]
Update. I ran the script line by line in the interpreter. This was the first line that errored:

>>> boardMACBytes = pimon.getBoardMAC().to_bytes(6, 'little')
[Errno 22] Invalid argument

**Comment by DennisFaucher** [comment]
Scratch that. I went through the VIB install process again, rebooted and now everything works :)

**Comment by thebel1** [comment]
Glad you got it to work!
