### ISSUE TITLE
Is there a way to get the temperature in X64?

### ISSUE THREAD

**Issue by huangsijun17** [thebel1/thpimon#7]
Can the script be ported to the X64 platform?

**Comment by nyx0** [comment]
ESXi Arm Edition is 64bits -> Build 18427252 VMware-VMvisor-Installer-7.0.0-18427252.**aarch64**.iso

**Comment by thebel1** [comment]
> Can the script be ported to the X64 platform?

If you mean x86-64 then no, simply porting it won't be enough. A new driver would have to be written for the specific target platform.

**Comment by huangsijun17** [comment]
> > Can the script be ported to the X64 platform?
> 
> If you mean x86-64 then no, simply porting it won't be enough. A new driver would have to be written for the specific target platform.

Thx
